apiVersion: v1
kind: PersistentVolume
metadata:
  name: changedetection-config-pv
  namespace: downloads
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: changedetection-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection-deployment
  namespace: downloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetection
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      initContainers:
      - name: set-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1999:1999 /datastore"]
        volumeMounts:
        - name: config-storage
          mountPath: /datastore    
      containers:
        - name: mailer
          image: boky/postfix
          env:
            - name: "ALLOWED_SENDER_DOMAINS"
              value: "cynexia.net"
            - name: "HOSTNAME"
              value: "changedetection.cynexia.net"
          ports:
            - name: smtp
              containerPort: 25
        - name: changedetection
          image: ghcr.io/dgtlmoon/changedetection.io:latest
          env:
            - name: PLAYWRIGHT_DRIVER_URL
              value: "ws://playwright-service:3000/?--disable-web-security=true" # Update this line
            - name: PUID
              value: "1999"
            - name: PGID
              value: "1999"
          ports:
            - name: web
              containerPort: 5000
          volumeMounts:
            - name: config-storage
              mountPath: /datastore  # Adjusted path
          securityContext:
            runAsNonRoot: true
            runAsUser: 1999
            allowPrivilegeEscalation: false
        - name: playwright
          image: browserless/chrome
          hostname: playwright
          env:
            - name: WORKSPACE_DELETE_EXPIRED
              value: "true"
            - name: WORKSPACE_EXPIRE_DAYS
              value: "2"
            - name: "HOST"
              value: "0.0.0.0"
            - name: SCREEN_WIDTH
              value: "1920"
            - name: SCREEN_HEIGHT
              value: "1024"
            - name: SCREEN_DEPTH
              value: "16"
            - name: ENABLE_DEBUGGER
              value: "false"
            - name: PREBOOT_CHROME
              value: "true"
            - name: CONNECTION_TIMEOUT
              value: "300000"
            - name: MAX_CONCURRENT_SESSIONS
              value: "10"
            - name: CHROME_REFRESH_TIME
              value: "600000"
            - name: DEFAULT_BLOCK_ADS
              value: "true"
            - name: DEFAULT_STEALTH
              value: "true"
          ports:
            - name: pw-container 
              containerPort: 3000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: changedetection-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: playwright-service
  namespace: downloads  # Replace with your desired namespace
spec:
  selector:
    app: changedetection  # Make sure this selector matches your WebSocket container's labels
  ports:
    - name: playwright
      protocol: TCP
      port: 3000
      targetPort: pw-container 
---
apiVersion: v1
kind: Service
metadata:
  name: changedetection-service
  namespace: downloads
spec:
  selector:
    app: changedetection
  type: NodePort
  ports:
  - name: cd-web-port
    protocol: TCP
    port: 443
    targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: changedetection-ingress
  namespace: downloads
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: changedetection.cynexia.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: changedetection-service
            port:
              name: cd-web-port
  tls:
  - hosts:
    - changedetection.cynexia.net
    secretName: changedetection.cynexia.net
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-loadbalancer-changedetection
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.17.245
  ports:
    - name: https-in
      protocol: TCP
      port: 443
      targetPort: 443