apiVersion: v1
kind: Service
metadata:
  name: emby-service
  namespace: downloads
spec:
  selector:
    app: emby
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
  - name: http-8096
    port: 8096
    protocol: TCP
    targetPort: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-emby
  namespace: downloads
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: emby.cynexia.net
    http:
      paths:
      - backend:
          service:
            name: emby-service
            port: 
              name: http-8096
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - emby.cynexia.net
    secretName: emby.cynexia.net
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-config-smb-pv
  namespace: downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/appdata/emby
  mountOptions:
  storageClassName: retain-local-path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k2.cynexia.net
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-config-smb-pvc
  namespace: downloads
spec:
  storageClassName: retain-local-path
  volumeName: emby-config-smb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-videos-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/video/"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-videos-nfs-pvc
  namespace: downloads
spec:
  volumeName: emby-videos-nfs-pv
  storageClassName: retain-local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  namespace: downloads
spec:
  selector:
    matchLabels:
      app: emby
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
      - env:
        - name: PGID
          value: "998"
        - name: PUID
          value: "110"
        - name: TZ
          value: Europe/London
        image: linuxserver/emby:latest
        imagePullPolicy: Always
        securityContext:
          runAsRoot: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false        
        name: emby
        ports:
        - containerPort: 8096
          name: 8096tcp01
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /mnt
          name: video
      restartPolicy: Always
      startupProbe:
        failureThreshold: 10
        httpGet:
          path: /
          port: 8096tcp01
          scheme: HTTP
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 5
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 8096tcp01
          scheme: HTTP
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: emby-config-smb-pvc
      - name: video
        persistentVolumeClaim:
          claimName: emby-videos-nfs-pvc