apiVersion: v1
kind: Service
metadata:
  name: emby-service
  namespace: downloads
spec:
  selector:
    app: emby
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
  - name: http-8096
    port: 8096
    protocol: TCP
    targetPort: 8096
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-emby
  namespace: downloads
spec:
  rules:
  - host: emby.cynexia.net
    http:
      paths:
      - backend:
          serviceName: emby-service
          servicePort: 8096
        path: /
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-config-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: fs.cynexia.net
    path: "/tank/appdata/emby/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-config-nfs-pvc
  namespace: downloads
spec:
  volumeName: emby-config-nfs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-videos-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/video/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-videos-nfs-pvc
  namespace: downloads
spec:
  volumeName: emby-videos-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  namespace: downloads
spec:
  selector:
    matchLabels:
      app: emby
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
      - env:
        - name: PGID
          value: "998"
        - name: PUID
          value: "110"
        - name: TZ
          value: Europe/London
        image: linuxserver/emby:latest
        imagePullPolicy: Always
        startupProbe:
          failureThreshold: 15
          httpGet:
            path: /
            port: 8096tcp02
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8096tcp02
            scheme: HTTP
          failureThreshold: 2
          periodSeconds: 10
        name: emby
        ports:
        - containerPort: 8096
          name: 8096tcp01
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8096
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 15
          successThreshold: 2
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /mnt
          name: video
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: emby-config-nfs-pvc
      - name: video
        persistentVolumeClaim:
          claimName: emby-videos-nfs-pvc
