kind: Service
apiVersion: v1
metadata:
  name: hydra-service
  namespace: downloads
spec:
  selector:
    app: hydra
  type: NodePort
  ports:
  - protocol: TCP
    port: 5076
    targetPort: 5076
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hydra-config-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/appdata/hydra/config"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hydra-config-nfs-pvc
  namespace: downloads
spec:
  volumeName: hydra-config-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: downloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - name: hydra
        image: linuxserver/hydra2:latest
        env:
        - name: PUID
          value: "99"
        - name: PGID
          value: "911"  
        ports:
        - containerPort: 5076
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: hydra-config-nfs-pvc
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-hydra
  namespace: downloads
spec:
  rules:
  - host: hydra.cynexia.net
    http:
      paths:
      - path: /
        backend:
          serviceName: hydra-service
          servicePort: 5076
