apiVersion: v1
kind: Service
metadata:
  name: ingress-loadbalancer-hydra
  namespace: ingress
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.100.0.249
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-service
  namespace: downloads
spec:
  ports:
  - name: hydra-web-port
    port: 443
    protocol: TCP
    targetPort: containerport
  selector:
    app: hydra
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hydra-ingress
  namespace: downloads
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: hydra.cynexia.net
    http:
      paths:
      - backend:
          service:
            name: hydra-service
            port:
              name: hydra-web-port
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - hydra.cynexia.net
    secretName: hydra.cynexia.net
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hydra-config-longhorn-pv
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  capacity:
      storage: 30Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: hydra-config
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra-config-longhorn-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
  volumeName: hydra-config-longhorn-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: downloads
spec:
  selector:
    matchLabels:
      app: hydra
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hydra
    spec:
      containers:
      - env:
        - name: PGID
          value: "1999"
        - name: PUID
          value: "1999"
        - name: TZ
          value: Europe/London
        image: linuxserver/nzbhydra2:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          # dropping capabilities seems to be incompatible with longhorn
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            - FOWNER
            - DAC_OVERRIDE
            - DAC_READ_SEARCH
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
        startupProbe:
          failureThreshold: 15
          httpGet:
            path: /
            port: containerport
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: containerport
            scheme: HTTP
          failureThreshold: 2
          periodSeconds: 10
        name: hydra
        ports:
        - containerPort: 5076
          name: containerport
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 5076
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 15
          successThreshold: 2
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: hydra-config-longhorn-pvc
