## see https://immich.app/docs/install/kubernetes
## install with
# helm install immich oci://ghcr.io/immich-app/immich-charts/immich -n immich -f immich-values.yaml
##
## upgrade with
# helm upgrade immich oci://ghcr.io/immich-app/immich-charts/immich -n immich -f immich-values.yaml
##

# External PostgreSQL configuration
postgresql:
  enabled: false  # Disable built-in PostgreSQL

image:
  tag: v2.0.1

env:
  DB_HOSTNAME: postgresql-service.immich.svc.cluster.local
  DB_USERNAME: postgres
  DB_DATABASE_NAME: postgres
  DB_PASSWORD: postgresql

# Storage configuration
immich:
  persistence:
    library:
      existingClaim: immich-upload-pvc  # Use separate Longhorn volume for uploads

# Mount NFS as external media for photo library
persistence:
  external-media:
    enabled: true
    existingClaim: immich-library-pvc
    globalMounts:
      - path: /mnt/media/ente
        readOnly: true


# Ingress configuration
server:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: photos.cynexia.net
          paths:
            - path: "/"
      tls:
        - hosts:
            - photos.cynexia.net
          secretName: photos.cynexia.net

# Keep Redis enabled (built-in)
redis:
  enabled: true
