apiVersion: v1
kind: Service
metadata:
  name: ingress-loadbalancer-jellyfin
  namespace: ingress
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.100.0.246
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: downloads
spec:
  selector:
    app: jellyfin
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
  - name: http-8096
    port: 443
    protocol: TCP
    targetPort: containerport
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jellyfin
  namespace: downloads
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: jellyfin.cynexia.net
    http:
      paths:
      - backend:
          service:
            name: jellyfin-service
            port: 
              name: http-8096
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - jellyfin.cynexia.net
    secretName: jellyfin.cynexia.net
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-longhorn-pv
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  capacity:
    storage: 100Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: jellyfin-config
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-longhorn-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
  volumeName: jellyfin-config-longhorn-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-videos-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  storageClassName: retain-local-path
  nfs:
    server: 10.10.10.1
    path: "/tank/video/"
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-videos-nfs-pvc
  namespace: downloads
spec:
  volumeName: jellyfin-videos-nfs-pv
  storageClassName: retain-local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: downloads
spec:
  selector:
    matchLabels:
      app: jellyfin
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - env:
        - name: PGID
          value: "1999"
        - name: PUID
          value: "1999"
        - name: TZ
          value: Europe/London
        image: linuxserver/jellyfin:latest
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: containerport
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: containerport
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          # dropping capabilities seems to be incompatible with longhorn
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            - FOWNER
            - DAC_OVERRIDE
            - DAC_READ_SEARCH
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
        name: jellyfin
        ports:
        - containerPort: 8096
          name: containerport
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /mnt
          name: video
        - mountPath: /transcode
          name: cache-vol
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config-longhorn-pvc
      - name: video
        persistentVolumeClaim:
          claimName: jellyfin-videos-nfs-pvc
      - name: cache-vol
        emptyDir:
          medium: Memory
          sizeLimit: 35Gi