# you can also create this manually
# kubectl create secret generic -n longhorn-system linode-secret \
# --from-literal=AWS_ACCESS_KEY_ID=AKIA...OMQ \
# --from-literal=AWS_SECRET_ACCESS_KEY=X...2Q
# --from-literal=AWS_ENDPOINTS=https://nl-ams-1.linodeobjects.com


apiVersion: v1
kind: Secret
metadata:
  name: linode-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: <key>== # base64 encoded
  AWS_ACCESS_KEY_ID: <secret>= # base64 encoded
  AWS_ENDPOINTS: https://nl-ams-1.linodeobjects.com
  
