# you can also create this manually
# kubectl create secret generic aws-secret \
# --from-literal=accessKey=<access key> \
# --from-literal=secretKey=<secret key>

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: <key>== # base64 encoded
  AWS_ACCESS_KEY_ID: <secret>= # base64 encoded
