apiVersion: v1
data:
  hsts: "true"
  hsts-include-subdomains: "true"
  hsts-max-age: "0"
  hsts-preload: "false"
kind: ConfigMap
metadata:
  name: nginx-load-balancer-microk8s-conf
  namespace: default