apiVersion: v1
kind: Namespace
metadata:
  name: downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/largeappdata/sabnzbd/complete"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads-nfs-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/video/movies"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: movies-nfs-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6Ti