apiVersion: v1
kind: Service
metadata:
  name: ingress-loadbalancer-radarr
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.17.253
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
kind: Service
apiVersion: v1
metadata:
  name: radarr-service
  namespace: downloads
spec:
  selector:
    app: radarr
  type: NodePort
  ports:
  - name: radarr-web-port
    protocol: TCP
    port: 443
    targetPort: containerport
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-radarr
  namespace: downloads
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: radarr.cynexia.net
    http:
      paths:
      - backend:
          service:
            name: radarr-service
            port:
              name: radarr-web-port
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - radarr.cynexia.net
    secretName: radarr.cynexia.net
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-longhorn-pv
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  capacity:
      storage: 20Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: radarr-config
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-longhorn-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeName: radarr-config-longhorn-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/video"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-media-nfs-pvc
  namespace: downloads
spec:
  volumeName: radarr-media-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 6Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: downloads
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      dnsPolicy: None
      containers:
      - name: radarr
        securityContext:
          allowPrivilegeEscalation: false
          # dropping capabilities seems to be incompatible with longhorn
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            - FOWNER
            - DAC_OVERRIDE
            - DAC_READ_SEARCH
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
        image: linuxserver/radarr:latest
        env:
        - name: PGID
          value: "1999"
        - name: PUID
          value: "1999"
        - name: TZ
          value: Europe/London
        ports:
        - containerPort: 7878
          protocol: TCP
          name: containerport
        startupProbe:
            failureThreshold: 15
            httpGet:
              path: /
              port: containerport
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        livenessProbe:
            httpGet:
              path: /
              port: containerport
              scheme: HTTP
            failureThreshold: 5
            periodSeconds: 10
        volumeMounts:
        - name: media
          mountPath: /media
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config-longhorn-pvc
      - name: media
        persistentVolumeClaim:
          claimName: radarr-media-nfs-pvc
