kind: Service
apiVersion: v1
metadata:
  name: sabnzbd-service
  namespace: downloads
spec:
  selector:
    app: sabnzbd
  type: NodePort
  ports:
  - name: sab-web-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-downloads-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/largeappdata/sabnzbd/complete"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-downloads-nfs-pvc
  namespace: downloads
spec:
  volumeName: sabnzbd-downloads-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 6Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/appdata/sabnzbd/config"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-config-nfs-pvc
  namespace: downloads
spec:
  volumeName: sabnzbd-config-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-watch-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/appdata/sabnzbd/watch"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-watch-nfs-pvc
  namespace: downloads
spec:
  volumeName: sabnzbd-watch-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 6Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-incomplete-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/largeappdata/sabnzbd/incomplete"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-incomplete-nfs-pvc
  namespace: downloads
spec:
  volumeName: sabnzbd-incomplete-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 6Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      dnsPolicy: None
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd:latest
        env:
        - name: PUID
          value: "110"
        - name: PGID
          value: "998"  
        ports:
        - containerPort: 8080
          protocol: TCP
          name: containerport
        startupProbe:
            failureThreshold: 15
            httpGet:
              path: /
              port: containerport
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        livenessProbe:
            httpGet:
              path: /
              port: containerport
              scheme: HTTP
            failureThreshold: 5
            periodSeconds: 10
        volumeMounts:
        - name: watch
          mountPath: /watch
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: incomplete
          mountPath: /incomplete-downloads
      volumes:
      - name: watch
        persistentVolumeClaim:
          claimName: sabnzbd-watch-nfs-pvc
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-config-nfs-pvc
      - name: downloads
        persistentVolumeClaim:
          claimName: sabnzbd-downloads-nfs-pvc
      - name: incomplete
        persistentVolumeClaim:
          claimName: sabnzbd-incomplete-nfs-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sabnzbd
  namespace: downloads
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: sab.cynexia.net
    http:
      paths:
      - backend:
          service:
            name: sabnzbd-service
            port:
              name: sab-web-port
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - sab.cynexia.net
    secretName: sab.cynexia.net
