kind: Service
apiVersion: v1
metadata:
  name: sabnzbd-service
  namespace: downloads
spec:
  selector:
    app: sabnzbd
  type: LoadBalancer
  loadBalancerIP: 192.168.17.251
  ports:
  - name: sab-web-port
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-media-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: pve2.cynexia.net
    path: "/tank/video"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retain-local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-media-nfs-pvc
  namespace: downloads
spec:
  volumeName: sabnzbd-media-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config-longhorn-pv
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  capacity:
      storage: 20Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sab-config
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-longhorn-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeName: sabnzbd-config-longhorn-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      dnsPolicy: None
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd:latest
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "110"
        - name: PGID
          value: "998"  
        securityContext:
          runAsRoot: false
          allowPrivilegeEscalation: false
          # dropping capabilities seems to be incompatible with longhorn
          #capabilities:
          #  add:
          #  - CHOWN
          #  - SETGID
          #  - SETUID
          #  drop:
          #  - ALL
          privileged: false
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8080
          protocol: TCP
          name: containerport
        startupProbe:
            failureThreshold: 15
            httpGet:
              path: /
              port: containerport
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        livenessProbe:
            httpGet:
              path: /
              port: containerport
              scheme: HTTP
            failureThreshold: 5
            periodSeconds: 10
        volumeMounts:
        - name: media
          mountPath: /media
        - name: config
          mountPath: /config
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: sabnzbd-media-nfs-pvc
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-config-longhorn-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-sabnzbd
  namespace: downloads
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: sab.cynexia.net
    http:
      paths:
      - backend:
          service:
            name: sabnzbd-service
            port:
              name: sab-web-port
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - sab.cynexia.net
    secretName: sab.cynexia.net
