kind: Service
apiVersion: v1
metadata:
  name: sabnzbd-service
  namespace: downloads
spec:
  selector:
    app: sabnzbd
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/appdata/sabnzbd/config"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-config-nfs-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: watch-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/appdata/sabnzbd/watch"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: watch-nfs-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: incomplete-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/largeappdata/sabnzbd/incomplete"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: incomplete-nfs-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 6Ti
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd:latest
        env:
        - name: PUID
          value: "99"
        - name: PGID
          value: "100"  
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: watch
          mountPath: /watch
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        - name: incomplete
          mountPath: /incomplete-downloads
      volumes:
      - name: watch
        persistentVolumeClaim:
          claimName: watch-nfs-pvc
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-config-nfs-pvc
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-nfs-pvc
      - name: incomplete
        persistentVolumeClaim:
          claimName: incomplete-nfs-pvc
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-sabnzbd
  namespace: downloads
spec:
  rules:
  - host: sab.cynexia.net
    http:
      paths:
      - path: /
        backend:
          serviceName: sabnzbd-service
          servicePort: 8080