---
apiVersion: v1
kind: Secret
metadata: { name: health-influxdb, namespace: health }
stringData:
  admin-password: "${HEALTH_INFLUX_ADMIN_PASSWORD}"
  admin-token: "${HEALTH_INFLUX_ADMIN_TOKEN}"
  garmin-v1-password: "${HEALTH_INFLUX_GARMIN_V1_PASSWORD}"
  ingester-token: "${HEALTH_INFLUX_INGESTER_TOKEN}"
  read-token: "${HEALTH_INFLUX_READ_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata: { name: health-hae, namespace: health }
stringData:
  auth-token: "${HEALTH_HAE_AUTH_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata: { name: health-garmin, namespace: health }
stringData:
  email: "${HEALTH_GARMIN_EMAIL}"
  b64-password: "${HEALTH_GARMIN_B64_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata: { name: health-pomerium, namespace: health }
stringData:
  google-client-id: "${HEALTH_POMERIUM_GOOGLE_CLIENT_ID}"
  google-client-secret: "${HEALTH_POMERIUM_GOOGLE_CLIENT_SECRET}"
  cookie-secret: "${HEALTH_POMERIUM_COOKIE_SECRET}"
  shared-secret: "${HEALTH_POMERIUM_SHARED_SECRET}"
---
apiVersion: v1
kind: Secret
metadata: { name: health-grafana, namespace: health }
stringData:
  admin-password: "${HEALTH_GRAFANA_ADMIN_PASSWORD}"
