apiVersion: v1
kind: Secret
metadata: { name: netdisco, namespace: netdisco }
stringData:
  pg-password: "${NETDISCO_PG_PASSWORD}"
  deployment.yml: |
    no_auth: false
    health_path: /health
    community: []
    community_rw: []
    devices_only:
      - 10.100.0.1
      - 192.168.17.10
      - 192.168.17.11
      - 192.168.17.12
      - 192.168.17.13
      - 192.168.17.14
      - 192.168.17.72
    device_auth:
      - tag: gateway_readonly
        community: "${NETDISCO_GATEWAY_SNMP_COMMUNITY}"
        read: true
        write: false
        only: 10.100.0.1
      - tag: switches_readonly
        community: "${NETDISCO_SWITCH_SNMP_COMMUNITY}"
        read: true
        write: false
        only:
          - 192.168.17.10
          - 192.168.17.11
          - 192.168.17.12
          - 192.168.17.13
          - 192.168.17.14
          - 192.168.17.72
