apiVersion: v1
kind: Secret
metadata:
  name: restic-b2
  namespace: backup
type: Opaque
stringData:
  B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
  B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
