apiVersion: v1
kind: Secret
metadata:
  name: homelab-proxy
  namespace: vps
type: Opaque
stringData:
  access-client-id: ${VPS_HOMELAB_PROXY_ACCESS_CLIENT_ID}
  access-client-secret: ${VPS_HOMELAB_PROXY_ACCESS_CLIENT_SECRET}
