apiVersion: v1
kind: Secret
metadata:
  name: restic-b2
  namespace: backup
type: Opaque
stringData:
  B2_ACCOUNT_ID: ${VPS_B2_ACCOUNT_ID}
  B2_ACCOUNT_KEY: ${VPS_B2_ACCOUNT_KEY}
  RESTIC_PASSWORD: ${VPS_RESTIC_PASSWORD}
  RESTIC_REPOSITORY: ${VPS_RESTIC_REPOSITORY}
