apiVersion: v1
kind: ConfigMap
metadata:
  name: proton-backup-config
  namespace: proton-backup
data:
  # Backup configuration
  BACKUP_SCHEDULE: "0 2 * * *"  # Daily at 2 AM
  TZ: "UTC"

  # Rclone configuration
  RCLONE_LOG_LEVEL: "INFO"
  RCLONE_CONFIG_FILE: "/config/rclone.conf"
  PROTON_REMOTE: "proton"
  LOCAL_PATH: "/data/proton"

  # Kopia configuration
  KOPIA_CONFIG_FILE: "/config/kopia.config"
  KOPIA_CACHE_DIR: "/config/cache"
  KOPIA_LOG_DIR: "/data/logs/kopia"
  KOPIA_USERNAME: "backup"
  KOPIA_HOSTNAME: "proton-backup-client"
  SOURCE_PATH: "/data/proton"

  # S3 configuration for Backblaze B2
  S3_ENDPOINT: "s3.eu-central-003.backblazeb2.com"
  S3_BUCKET: "cloud-files-backup"
  S3_REGION: "eu-central-003"

  # Healthcheck configuration
  HEALTHCHECK_URL: "https://hc-ping.com"
  HEALTHCHECK_UUID: "00528ad5-0f6a-4193-aeb0-7b980fccbe5f"

  # Resource limits for backup jobs
  BACKUP_TIMEOUT: "6h"
  MAX_PARALLEL_UPLOADS: "4"

  # Future: Email notifications could be added here