#!/usr/bin/env python3
"""Assert every standalone `kind: Job` sets `spec.ttlSecondsAfterFinished`.

A Job's `spec.template` is immutable. A completed Job that is never garbage
collected therefore pins the version of itself that ran, and the next apply
that changes it fails with `field is immutable`. Because `kubectl apply`
carries on past a failed resource and signals only through its exit code, the
breakage is quiet: everything else applies and the Job silently does not. The
homelab `restic-init` Job lacked the field and broke `diff-homelab` and
`apply-homelab` for 130 days before anyone noticed. `ttlSecondsAfterFinished`
is the prevention; this check is what stops the next Job from omitting it.

Jobs generated by a CronJob are OUT OF SCOPE. Each run gets a unique name, so
they never collide with each other, and pile-up is already bounded by
`successfulJobsHistoryLimit`. Only top-level `kind: Job` resources are checked.

This runs on raw `kustomize build` output, NOT the secret-rendered stream, so
it needs no 1Password access and no cluster access. Secret values are still
`${VAR}` placeholders at this point, which is exactly what we want: the check
is safe to run anywhere, including in CI.

Usage:
  scripts/check-job-ttl.py [cluster ...]      default: homelab vps

Exit status:
  0  every standalone Job sets the field
  1  at least one Job is missing it (each reported as `<cluster> <ns>/<name>`)
  2  the check itself could not run (kustomize missing or a build failed)
"""
import re
import subprocess
import sys

DEFAULT_CLUSTERS = ("homelab", "vps")
FIELD = "ttlSecondsAfterFinished"

# `kustomize build` emits normalised block YAML: one resource per document,
# documents separated by a bare `---` at column 0, top-level keys at column 0
# and their immediate children at exactly two spaces. Nothing here uses
# anchors, merge keys or flow mappings. Both parsers below rely only on that.

try:
    import yaml
except ImportError:
    # PyYAML is not in the stdlib and is absent from stock macOS and Homebrew
    # python3. Rather than make the check unrunnable, or make the repo carry a
    # virtualenv for one assertion, fall back to the structural scan below.
    yaml = None


def jobs_via_yaml(text):
    """Yield (namespace, name, has_ttl) using a real YAML parse."""
    for doc in yaml.safe_load_all(text):
        if not isinstance(doc, dict) or doc.get("kind") != "Job":
            continue
        meta = doc.get("metadata") or {}
        spec = doc.get("spec") or {}
        yield (meta.get("namespace", "default"),
               meta.get("name", "<unnamed>"),
               spec.get(FIELD) is not None)


# A top-level key: `kind:` / `metadata:` / `spec:` at column 0.
TOP_KEY = re.compile(r"^([A-Za-z][A-Za-z0-9_]*):(?:\s+(.*))?$")
# A second-level key at EXACTLY two spaces of indent. The exact-indent rule is
# what keeps a nested `name:` inside spec.template out of the results, and what
# keeps `kind: Job` nested inside a CronJob's jobTemplate from matching.
SUB_KEY = re.compile(r"^ {2}([A-Za-z][A-Za-z0-9_]*):(?:\s+(.*))?$")


def jobs_via_scan(text):
    """Yield (namespace, name, has_ttl) without PyYAML.

    Safe on `kustomize build` output specifically, because a document
    separator and a top-level key only ever appear at column 0 there: block
    scalars (the embedded shell and Python) are always indented, so no line of
    embedded content can be mistaken for structure.
    """
    for doc in re.split(r"(?m)^---$", text):
        kind = section = None
        meta, spec = {}, {}
        for line in doc.splitlines():
            top = TOP_KEY.match(line)
            if top:
                section = top.group(1)
                if section == "kind":
                    kind = (top.group(2) or "").strip()
                continue
            sub = SUB_KEY.match(line)
            if sub and section in ("metadata", "spec"):
                target = meta if section == "metadata" else spec
                target[sub.group(1)] = (sub.group(2) or "").strip()
        if kind == "Job":
            yield (meta.get("namespace", "default"),
                   meta.get("name", "<unnamed>"),
                   FIELD in spec)


def build(cluster):
    try:
        # check=False: a non-zero build is reported below with its stderr,
        # which is far more useful than a CalledProcessError traceback.
        out = subprocess.run(["kustomize", "build", cluster], check=False,
                             capture_output=True, text=True, timeout=180)
    except FileNotFoundError:
        sys.exit("ERROR: kustomize not on PATH")
    except subprocess.TimeoutExpired:
        sys.exit("ERROR: `kustomize build %s` timed out after 180s" % cluster)
    if out.returncode != 0:
        sys.exit("ERROR: `kustomize build %s` failed:\n%s"
                 % (cluster, out.stderr.strip()[:2000]))
    return out.stdout


def main(argv):
    clusters = argv[1:] or list(DEFAULT_CLUSTERS)
    find = jobs_via_yaml if yaml is not None else jobs_via_scan

    offenders, checked = [], 0
    for cluster in clusters:
        for namespace, name, has_ttl in find(build(cluster)):
            checked += 1
            if not has_ttl:
                offenders.append("%s %s/%s" % (cluster, namespace, name))

    if offenders:
        print("Job(s) missing spec.%s:\n" % FIELD)
        for offender in offenders:
            print("  %s" % offender)
        print("\nA completed Job without a TTL is never garbage collected, and "
              "its\nimmutable spec.template then makes every later apply that "
              "changes it fail\nquietly. See AGENTS.md.")
        return 1

    print("OK: %d standalone Job(s) across %s all set spec.%s"
          % (checked, ", ".join(clusters), FIELD))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
