apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: downloads
spec:
  selector:
    app: jellyfin
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
  - name: http-8097
    port: 8096
    protocol: TCP
    targetPort: 8096
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jellyfin
  namespace: downloads
spec:
  rules:
  - host: jellyfin.cynexia.net
    http:
      paths:
      - backend:
          serviceName: jellyfin-service
          servicePort: 8096
        path: /
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    server: fs.cynexia.net
    path: "/tank/appdata/jellyfin/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-config-nfs-pvc
  namespace: downloads
spec:
  volumeName: jellyfin-config-nfs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-videos-nfs-pv
  namespace: downloads
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs.cynexia.net
    path: "/tank/video/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-videos-nfs-pvc
  namespace: downloads
spec:
  volumeName: jellyfin-videos-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: downloads
spec:
  selector:
    matchLabels:
      app: jellyfin
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - env:
        - name: PGID
          value: "10"
        - name: PUID
          value: "911"
        - name: TZ
          value: Europe/London
        image: linuxserver/jellyfin:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8096
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: jellyfin
        ports:
        - containerPort: 8096
          name: 8096tcp01
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8096
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: video
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config-nfs-pvc
      - name: video
        persistentVolumeClaim:
          claimName: jellyfin-videos-nfs-pvc